name: Build Check(Windows)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'  # Use latest stable version

      - name: Verify Go installation
        run: go version

      - name: Check go.mod exists
        run: |
          if not exist go.mod (
            echo "❌ go.mod not found!"
            exit /b 1
          )
          echo "✅ go.mod found"

      - name: Install Go dependencies
        run: |
          echo "Downloading dependencies..."
          go mod download -x
          echo "Dependencies downloaded successfully"

      - name: Run build script
        run: scripts\build.bat

      - name: Check if EXE was generated
        run: |
          if not exist dist\click-guardian-gui.exe (
            echo "❌ GUI EXE not found!"
            exit /b 1
          )
          if not exist dist\click-guardian.exe (
            echo "❌ Console EXE not found!"
            exit /b 1
          )
          echo "✅ Both EXE files found."