name: Build Check(Windows)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.24'  # Alt: Use latest stable version go-version: 'stable'

      - name: Verify Go installation
        run: go version

      - name: Check go.mod exists
        run: |
          if (-not (Test-Path "go.mod")) {
            Write-Host "❌ go.mod not found!"
            exit 1
          }
          Write-Host "✅ go.mod found"

      - name: Install Go dependencies
        run: |
          Write-Host "Downloading dependencies..."
          go mod download -x
          Write-Host "Dependencies downloaded successfully"

      - name: Check if EXE was generated
        run: |
          if (-not (Test-Path "dist\click-guardian-gui.exe")) {
            Write-Host "❌ GUI EXE not found!"
            exit 1
          }
          if (-not (Test-Path "dist\click-guardian.exe")) {
            Write-Host "❌ Console EXE not found!"
            exit 1
          }
          Write-Host "✅ Both EXE files found."